project_id = "tcxvcatsqqertcnycuop"

[functions.notify-event]
verify_jwt = false

[functions.whatsapp-otp]
verify_jwt = false

[functions.public-order-tracking]
verify_jwt = false

[functions.whatsapp-webhook]
verify_jwt = false

[functions.whatsapp-message-stitcher]
verify_jwt = false

[functions.banyan-central-parser]
verify_jwt = false

[functions.generate-bi-monthly-ledger]
verify_jwt = false

[functions.generate-rescue-ledger]
verify_jwt = false

[functions.oasis-ai-chat]
verify_jwt = false

[functions.msg91-otp]
verify_jwt = false

[functions.msg91-webhook]
verify_jwt = false

[functions.validate-user]
verify_jwt = false

[functions.send-whatsapp]
verify_jwt = false

[functions.send-whatsapp-automation]
verify_jwt = false
