import type { WriteActionKind } from "./writeActionKinds";
import type { WriteActionAuthority } from "./writeAuthorityTypes";

/** Static authority matrix — enforcement belongs in API middleware later. */
export const WRITE_AUTHORITY: Record<WriteActionKind, WriteActionAuthority> = {
  "retail.reservation_draft.create": {
    kind: "retail.reservation_draft.create",
    requiredRole: "store_operator",
    requiresHumanConfirmation: true,
    requiresAudit: true,
    requiresIdempotencyKey: true,
    rollbackKind: "soft_delete",
    allowedEnvironments: ["development", "staging"],
    featureFlagKey: "ENABLE_RETAIL_RESERVATION_WRITES",
  },
  "retail.reservation_draft.cancel": {
    kind: "retail.reservation_draft.cancel",
    requiredRole: "store_operator",
    requiresHumanConfirmation: true,
    requiresAudit: true,
    requiresIdempotencyKey: true,
    rollbackKind: "state_revert",
    allowedEnvironments: ["development", "staging"],
    featureFlagKey: "ENABLE_RETAIL_RESERVATION_WRITES",
  },
  "retail.factory_followup.create": {
    kind: "retail.factory_followup.create",
    requiredRole: "store_operator",
    requiresHumanConfirmation: true,
    requiresAudit: true,
    requiresIdempotencyKey: true,
    rollbackKind: "soft_delete",
    allowedEnvironments: ["development", "staging"],
    featureFlagKey: "ENABLE_FACTORY_FOLLOWUP_WRITES",
  },
  "media.attachment_metadata.create": {
    kind: "media.attachment_metadata.create",
    requiredRole: "cmd",
    requiresHumanConfirmation: true,
    requiresAudit: true,
    requiresIdempotencyKey: true,
    rollbackKind: "soft_delete",
    allowedEnvironments: ["development", "staging", "production"],
    featureFlagKey: "ENABLE_MEDIA_METADATA_WRITES",
  },
  "notification.acknowledge": {
    kind: "notification.acknowledge",
    requiredRole: "store_operator",
    requiresHumanConfirmation: false,
    requiresAudit: true,
    requiresIdempotencyKey: true,
    rollbackKind: "compensating_movement",
    allowedEnvironments: ["development", "staging", "production"],
    featureFlagKey: "ENABLE_NOTIFICATION_ACK_WRITES",
  },
  "inventory.reservation_hold.request": {
    kind: "inventory.reservation_hold.request",
    requiredRole: "inventory_controller",
    requiresHumanConfirmation: true,
    requiresAudit: true,
    requiresIdempotencyKey: true,
    rollbackKind: "compensating_movement",
    allowedEnvironments: ["development", "staging"],
    featureFlagKey: "ENABLE_INVENTORY_HOLD_WRITES",
  },
  "inventory.reconciliation_note.create": {
    kind: "inventory.reconciliation_note.create",
    requiredRole: "inventory_controller",
    requiresHumanConfirmation: true,
    requiresAudit: true,
    requiresIdempotencyKey: true,
    rollbackKind: "soft_delete",
    allowedEnvironments: ["development", "staging"],
    featureFlagKey: "ENABLE_INVENTORY_HOLD_WRITES",
  },
  "approval.request.create": {
    kind: "approval.request.create",
    requiredRole: "finance",
    requiresHumanConfirmation: true,
    requiresAudit: true,
    requiresIdempotencyKey: true,
    rollbackKind: "state_revert",
    allowedEnvironments: ["development", "staging", "production"],
    featureFlagKey: "ENABLE_APPROVAL_REQUEST_WRITES",
  },
};
