import type { Point100UpstreamDependency } from "./upstreamDependencies";

/** Live upstream census — software lanes merged per 2026-09-19 reconciliation; external evidence remains physical_uat_only. */
export const POINT100_UPSTREAM_DEPENDENCIES: readonly Point100UpstreamDependency[] = [
  {
    id: "central-macro-ops-556",
    repository: "Oasis-Baklawa-Central",
    pr: "#556",
    state: "merged",
    affectedStageIds: [
      "packing_cartons_dpl",
      "final_invoice_balance",
      "finance_dispatch_clearance",
      "dispatch_consignment",
      "security_gate",
      "customer_dispatch_proof",
    ],
    blockerDetail: "Central Order→Factory→Packing→Dispatch→Gate journey merged (#556).",
    failClosedStatus: "implemented",
  },
  {
    id: "central-macro-management-558",
    repository: "Oasis-Baklawa-Central",
    pr: "#558",
    state: "merged",
    affectedStageIds: ["finance_verification_reconciliation", "final_invoice_balance", "finance_dispatch_clearance"],
    blockerDetail: "Management macro #558 merged to Central main.",
    failClosedStatus: "implemented",
  },
  {
    id: "central-auth-buyer-588",
    repository: "Oasis-Baklawa-Central",
    pr: "#588",
    state: "merged",
    affectedStageIds: ["buyer_catalogue_intent", "buyer_quotation_so"],
    blockerDetail: "Central AUTH-01 post-claim Buyer role reconciliation merged (#588).",
    failClosedStatus: "implemented",
  },
  {
    id: "central-ai-chat-591",
    repository: "Oasis-Baklawa-Central",
    pr: "#591",
    state: "merged",
    affectedStageIds: ["buyer_catalogue_intent"],
    blockerDetail: "Central oasis-ai-chat authenticated staff consumer merged (#591).",
    failClosedStatus: "implemented",
  },
  {
    id: "core-buyer-auth-326",
    repository: "oasis-supabase-core",
    pr: "#326",
    state: "merged",
    affectedStageIds: ["buyer_catalogue_intent", "buyer_quotation_so"],
    blockerDetail: "Core Buyer RPC identity hardening merged (#326).",
    failClosedStatus: "implemented",
  },
  {
    id: "core-inventory-macro-256",
    repository: "oasis-supabase-core",
    pr: "#256",
    state: "merged",
    affectedStageIds: ["inventory_lot_allocation", "production_qc"],
    blockerDetail: "Macro Inventory #256 on production-certified Core pin.",
    failClosedStatus: "implemented",
  },
  {
    id: "core-finance-ledger-321",
    repository: "oasis-supabase-core",
    pr: "#321",
    state: "merged",
    affectedStageIds: ["finance_verification_reconciliation", "final_invoice_balance"],
    blockerDetail: "Core Finance ledger merged (#321); Edge functions active in production.",
    failClosedStatus: "implemented",
  },
  {
    id: "core-macro-trace-259",
    repository: "oasis-supabase-core",
    pr: "#259",
    state: "merged",
    affectedStageIds: ["trace_handover"],
    blockerDetail: "Macro Trace Core #259 authority on production pin.",
    failClosedStatus: "implemented",
  },
  {
    id: "core-trace-authority-300",
    repository: "oasis-supabase-core",
    pr: "#300",
    state: "merged",
    affectedStageIds: ["trace_handover"],
    blockerDetail: "Core Trace authority merged (#300); migration 20260915200000 on production pin.",
    failClosedStatus: "implemented",
  },
  {
    id: "core-security-hardening-307",
    repository: "oasis-supabase-core",
    pr: "#307",
    state: "merged",
    affectedStageIds: ["buyer_catalogue_intent"],
    blockerDetail: "Core staff_provisionable_roles RLS hardening merged (#307).",
    failClosedStatus: "implemented",
  },
  {
    id: "core-macro-dispatch-260",
    repository: "oasis-supabase-core",
    pr: "#260",
    state: "merged",
    affectedStageIds: ["dispatch_consignment", "order_complete"],
    blockerDetail: "Core #260 release_order_to_dispatched_v1 on production pin #182.",
    failClosedStatus: "implemented",
  },
  {
    id: "core-trace-reprint-290",
    repository: "oasis-supabase-core",
    pr: "#290",
    state: "merged",
    affectedStageIds: ["trace_handover"],
    blockerDetail: "Core #290 Trace reprint authority on production pin.",
    failClosedStatus: "implemented",
  },
  {
    id: "core-wa-consumer-328",
    repository: "oasis-supabase-core",
    pr: "#328",
    state: "merged",
    affectedStageIds: ["buyer_catalogue_intent"],
    blockerDetail: "Core WhatsApp consumer/worker merged (#328); production functions active.",
    failClosedStatus: "implemented",
  },
  {
    id: "core-wa-identity-309",
    repository: "oasis-supabase-core",
    pr: "#309",
    state: "merged",
    affectedStageIds: ["buyer_catalogue_intent"],
    blockerDetail: "Core WhatsApp identity merged (#309); webhook certified.",
    failClosedStatus: "implemented",
  },
  {
    id: "core-ai-chat-capture-329",
    repository: "oasis-supabase-core",
    pr: "#329",
    state: "merged",
    affectedStageIds: ["buyer_catalogue_intent"],
    blockerDetail: "Core AI chat capture merged (#329).",
    failClosedStatus: "implemented",
  },
  {
    id: "ai-studio-217",
    repository: "oasis-ai-studio",
    pr: "#217",
    state: "merged",
    affectedStageIds: ["buyer_catalogue_intent"],
    blockerDetail: "AI Studio #217 merged.",
    failClosedStatus: "implemented",
  },
  {
    id: "ai-studio-218",
    repository: "oasis-ai-studio",
    pr: "#218",
    state: "merged",
    affectedStageIds: ["buyer_catalogue_intent"],
    blockerDetail: "AI Studio #218 merged.",
    failClosedStatus: "implemented",
  },
  {
    id: "ai-alias-session-220",
    repository: "oasis-ai-studio",
    pr: "#220",
    state: "merged",
    affectedStageIds: ["buyer_catalogue_intent"],
    blockerDetail: "AI alias session #220 merged (supersedes #219).",
    failClosedStatus: "implemented",
  },
  {
    id: "buyer-app-recert",
    repository: "oasis-baklawa",
    pr: "main",
    state: "merged",
    affectedStageIds: ["buyer_catalogue_intent", "buyer_quotation_so"],
    blockerDetail: "Buyer app current main 4e5ec846 with backend-authority guard green.",
    failClosedStatus: "implemented",
  },
  {
    id: "oasis-trace-macro-37",
    repository: "oasis-trace",
    pr: "#37",
    state: "merged",
    affectedStageIds: ["trace_handover"],
    blockerDetail: "Trace #37 merged at 894f27327381ce168d168530eba3c3722d71eaee.",
    failClosedStatus: "implemented",
  },
  {
    id: "oasis-trace-recovery-38",
    repository: "oasis-trace",
    pr: "#38",
    state: "merged",
    affectedStageIds: ["trace_handover"],
    blockerDetail: "Trace #38 Point95/99 recovery lane merged 2026-09-19 against Core #290 production authority.",
    failClosedStatus: "implemented",
  },
  {
    id: "core-production-migration-182",
    repository: "oasis-supabase-core",
    pr: "#182",
    state: "merged",
    affectedStageIds: [
      "finance_dispatch_clearance",
      "dispatch_consignment",
      "security_gate",
      "trace_handover",
      "customer_dispatch_proof",
      "order_complete",
    ],
    blockerDetail: "Protected Production Migration Release #182 / run 34661721779 on Core SHA 7b2a09d4.",
    failClosedStatus: "implemented",
  },
  {
    id: "external-physical-provider-evidence",
    repository: "programme",
    pr: "physical-UAT",
    state: "physical_uat_only",
    affectedStageIds: ["trace_handover", "security_gate", "advance_payable_payment"],
    blockerDetail:
      "Scanner/printer/TV/handheld/mobile Gatekeeper, Buyer-phone, payment/provider and bank reconciliation require real device/provider evidence; Point100 software rehearsal does not fabricate PASS.",
    failClosedStatus: "physical_uat_only",
  },
] as const;
