/** Distinctive primary alias per Batch 001 SKU for resolver simulation (live-shaped, read-only audit). */
export const BATCH001_PRIMARY_ALIASES: Record<string, string> = {
  "OAS-AS-BKL-0001": "Cashew Kitta Lebanese Baklava",
  "OAS-AS-BKL-0002": "Square Baklawa",
  "OAS-AS-BKL-0003": "Cashew Ring Lebanese Baklava",
  "OAS-AS-BKL-0004": "Cashew Rosebud",
  "OAS-AS-BKL-0005": "Almond Crosole",
  "OAS-AS-BKL-0006": "Cashew Pyramid",
  "OAS-AS-BKL-0007": "Cashew Finger Lebanese Baklava",
  "OAS-AS-BKL-0008": "Date Baklawa",
  "OAS-AS-BKL-0009": "Special Square Baklawa",
  "OAS-AS-BKL-0010": "Pistachio Ring Lebanese Baklava",
  "OAS-AS-BKL-0011": "Pistachio Pyramid Topping",
  "OAS-AS-BKL-0012": "Chocolate Pistachio Asiyah Lebanese Baklava",
  "OAS-AS-BKL-0013": "Chocolate Cashew Asiyah Lebanese Baklava",
  "OAS-AS-BKL-0014": "Mor Cashew Asiyah Lebanese Baklava",
  "OAS-AS-BKL-0015": "Mor Pistachio Asiyah Lebanese Baklava",
  "OAS-AS-BKL-0016": "Pistachio Asiyah Lebanese Baklava",
  "OAS-AS-BKL-0017": "Cashew Asiyah Lebanese Baklava",
  "OAS-AS-BKL-0018": "Diamond Pistachio",
  "OAS-AS-BKL-0019": "Pistachio Pyramid Lebanese Baklava",
  "OAS-AS-BKL-0020": "Tart Cashew Lebanese Baklava",
  "OAS-AS-BKL-0021": "Mix Nut Tart Lebanese Baklava",
  "OAS-AS-BKL-0022": "Almond Tart Lebanese Baklava",
  "OAS-AS-BKL-0023": "Pistachio Tart Lebanese Baklava",
  "OAS-AS-BKL-0024": "Mor Pistachio Durum Turkish Baklava",
  "OAS-AS-BKL-0025": "Coconut Durum Turkish Baklava",
};
