// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
  realtime: {
    // Realtime temporarily disabled — fall back to REST polling/refetch.
    // Throttle events to a minimum and prevent automatic reconnect storms.
    params: {
      eventsPerSecond: 1,
    },
    reconnectAfterMs: () => 1_000_000_000, // effectively never reconnect
    heartbeatIntervalMs: 1_000_000_000,
  } as any,
});

// Hard-disable realtime: stub out channel creation so no WebSocket is opened.
try {
  const noopChannel: any = {
    on: () => noopChannel,
    subscribe: (cb?: (status: string) => void) => {
      try { cb?.("CLOSED"); } catch {}
      return noopChannel;
    },
    unsubscribe: () => Promise.resolve("ok"),
    send: () => {},
    topic: "realtime:disabled",
  };
  (supabase as any).channel = () => noopChannel;
  (supabase as any).removeChannel = () => Promise.resolve("ok");
  (supabase as any).removeAllChannels = () => Promise.resolve("ok");
  (supabase as any).getChannels = () => [];
  // Prevent the underlying socket from connecting
  const rt: any = (supabase as any).realtime;
  if (rt) {
    rt.connect = () => {};
    try { rt.disconnect?.(); } catch {}
  }
} catch (err) {
  console.warn("[supabase] realtime disable shim failed", err);
}
